### ISSUE TITLE
disabled option support

### ISSUE THREAD

**Issue by prototype-59** [fabianlindfors/multi.js#14]
Again, great plugin. Thank you. it would be nice if you could add support for selected  but "disabled" options. For example, a list contains names of people in a sales team and manager's name is "disabled" so it cannot be moved e.g.
```javascript
<option value="manager" selected disabled>Manager</option>
```
I have made some changes in your minimized code to support this feature , so perhaps you can make use of it if you want to make it an "official" feature.
```javascript
b.find("option").each(function(){
  var b=a(this),c=b.prop("value"),d=b.text(),f=b.is(":selected"),g=b.is(":disabled"); 
  e.push({value:c,label:d,selected:f,disabled:g, element:b})									
}),
```
and
```javascript
if(c.selected){
  e.addClass("selected");
  if(c.disabled){ e.removeClass("selected").addClass("disabled"); } 
  var f=e.clone();
  f.click(function(){
    if(!c.disabled) { c.element.prop("selected",!1), b.change()
  }
}),
```
I guess, a similar thing should be done for a keyboard events handler. 
Also in css i defined disabled class as:
```javascript
.multi-wrapper .item.disabled {
    color:#ccc;
}
```
This is just a quick fix - it can be done much better :-)

**Comment by fabianlindfors** [comment]
This should definitely be part of multi.js, hadn't even thought of it!

Will implement this soon. Thanks for bringing it up. :)

**Comment by fabianlindfors** [comment]
Hello again!

I just pushed e57b5065691fe1de14fcc918145cedfae0ca3165 which adds support for disabled options. The disabled options are by default displayed with a strikethrough but that can easily be overrriden with some CSS.

Thank you for your suggestion. :)
