### ISSUE TITLE
how to refresh plugin

### ISSUE THREAD

**Issue by wk199251248** [fabianlindfors/multi.js#15]
when ajax reload data, what's the refresh method?

**Comment by fabianlindfors** [comment]
Hi!

multi.js always follows the state of the select element it's been created from. If you are inserting options in the select using AJAX you need to trigger the `change` event on the select element. multi.js listens for this event and updates itself when triggered.

This has been previously discussed in issue #8 and I'm working on making it a bit easier. Here's how it can be done currently with jQuery:
```
var $select $( 'select' );
$select.multi();

// Trigger change event after updating original select element
$select.trigger( 'change' );
```

**Comment by juanadamuzsimj** [comment]
> Hi!
> 
> multi.js always follows the state of the select element it's been created from. If you are inserting options in the select using AJAX you need to trigger the `change` event on the select element. multi.js listens for this event and updates itself when triggered.
> 
> This has been previously discussed in issue #8 and I'm working on making it a bit easier. Here's how it can be done currently with jQuery:
> 
> ```
> var $select $( 'select' );
> $select.multi();
> 
> // Trigger change event after updating original select element
> $select.trigger( 'change' );
> ```

Its still not working...


$("#tarifas").val([1,2,3]);
$("#tarifas").multi();
$("#tarifas").trigger( 'change' );

Not updating selected box

**Comment by fabianlindfors** [comment]
@juanadamuzsimj Could you explain a bit what you're aiming to achieve with that code? Running `trigger` straight after initializing multi will not make any difference. `change` should be triggered after the underlying select element has changed in some way, for example after loading new elements using AJAX.

**Comment by rr-mdalauddin-alamin** [comment]
@fabianlindfors we just want to add one more item as selected after json 200 response

**Comment by fabianlindfors** [comment]
@alaminshakeel Sorry about the late reply. In this case, it should be enough to set the underlying `option` element as selected and then trigger the `change` event to make multi.js update itself!

**Comment by ritwick-pixel** [comment]
This worked for me:

**STEP 1 (Initialte multi in $(document).ready):**
```
$('#my_select_id').multi();
```

**STEP 2 (Change the value on fly):**
```
$(".multi-wrapper").remove();
$('#my_select_id').removeAttr("data-multijs");
var vl= [2,5,3];
$("#my_select_id").val(vl);
$('#my_select_id').multi();
```

**Comment by rr-mdalauddin-alamin** [comment]
Thanks. for me too.

Regards,
*Md. Alauddin Al-Amin*
Senior Backend Engineer.
Venturas Ltd <https://www.venturas-bd.com/>
cell: 8801672465250
