### ISSUE TITLE
There is no git tags on GitHub repository

### ISSUE THREAD

**Issue by sufuf3** [fabianlindfors/multi.js#16]
Hi @Fabianlindfors ,
We are cdnjs team, we're going to host this library.
The git auto-updater in [cdnjs](https://github.com/cdnjs/cdnjs) relies on [**git tags**](https://github.com/Fabianlindfors/multi.js/tags) so that it can recognize the correct version and automatically update the repo.
Could you please add git tags for the repo? 

And could you please help me add more information into `package.json` to upstream?
eg. `description`, `keywords`, `license`, `author`, `repository` ... etc.
ref: https://docs.npmjs.com/files/package.json

If you have any suggestions, please let me know.
Thank you.

cdnjs/cdnjs#10550

**Comment by fabianlindfors** [comment]
Hi!

I'm glad you want to add multi.js to your super useful service. I added the information you requested to package.json here 70bca559346552fc5d72f44d1b04e8712a9fed04 and also created a release for version 0.2.3.

Do you need anything else from me?

**Comment by sufuf3** [comment]
Wow, It's great!
@Fabianlindfors Thank you very much! 👍
