### ISSUE TITLE
Missing tag for 0.2.4

### ISSUE THREAD

**Issue by nijel** [fabianlindfors/multi.js#19]
The tag for the 0.2.4 release seems to be missing on GitHub and thus is not available in yarn. Can you please add/push it?

**Comment by fabianlindfors** [comment]
Hi! I'm sorry about this awfully late reply. Multi.js has unfortunately been deprioritized by me lately but I'm hoping to get back on it.

Is this still an issue? What kind of tag do you need added?

Thank you for your patience!

**Comment by fabianlindfors** [comment]
I just realised you probably meant that 0.2.4 wasn't available on npm/yarn! I just published it and it should be available. Thanks for pointing it out!
