### ISSUE TITLE
Search is not working when there are optgroup

### ISSUE THREAD

**Issue by pangeaos** [fabianlindfors/multi.js#23]
![screen shot 2018-11-12 at 22 31 36](https://user-images.githubusercontent.com/221474/48391110-c0f71280-e6ca-11e8-8f01-7e271b390c63.png)

**Comment by fabianlindfors** [comment]
Hi!

Big thanks for pointing this out. It's been fixed in 1.4.1 (e2c5ee973932a39fd16d251664793b050d73b916).

**Comment by pangeaos** [comment]
Thank you.

npm install multi.js@0.4.1
npm ERR! code ETARGET
npm ERR! notarget No matching version found for multi.js@0.4.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by fabianlindfors** [comment]
Whops! Had forgotten to publish to npm. Please try again! :)
