### ISSUE TITLE
preserve selected order

### ISSUE THREAD

**Issue by raffaeletani** [fabianlindfors/multi.js#24]
Is there an option to preserve the order in wich the items are selected?
right now it keeps the selected column ordered like the available column

**Comment by fabianlindfors** [comment]
Unfortunately, no. I've designed multi.js to stay very close to the underlying select element. The problem with this is that a regular select has no concept of which order the elements were selected. As a result it is not possible to preserve the selected order and it would be a bit of work to implement.

I'll keep your suggestion in mind though!

**Comment by kalimu** [comment]
This request has my vote for reconsidering :)
This could help a lot when one would like to use some kind of ranks as an input. The UI is already there.
