### ISSUE TITLE
No update on new data in the list; Not handling properly list changes when we click on the elements.

### ISSUE THREAD

**Issue by AlexisTM** [fabianlindfors/multi.js#29]
I have a similar problem to #20 with VueJS.  
The data is loaded dynamically with Vue but as no element was available at first, I added a dummy.

        <select multiple id="light-select">
                <option v-bind:value="value.name" v-for="value in lights">{{value.name}}</option>
                <option >ohoh</option>
        </select>

Yet, once I click on the dummy, it refreshes the data but it selects the *first element in the real list* and not the dummy.

**Comment by fabianlindfors** [comment]
I'm sorry for this insanely late reply. I've never tried multi.js with Vue myself. Did you find a solution for this?

**Comment by AlexisTM** [comment]
It happens to be late on single comments ;) 

I don't think I had a solution and instead made it myself in a VueJS way.

I guess that the issue comes from the options being shadowed on load of the page, when the options are not yet generated from VueJS side.

**Comment by fabianlindfors** [comment]
Yup, definitely slipped my mind :)

I wish I had more time to work on multi.js these days but I will look into it if I do find some!
