### ISSUE TITLE
Optgroup Support

### ISSUE THREAD

**Issue by andrew-pause** [fabianlindfors/multi.js#3]
Love the simplicity of this plugin, it would be great to have optgroup support though

**Comment by fabianlindfors** [comment]
Hadn't even thought of this, great idea!

Will implement this as soon as possible. :)

**Comment by xermus** [comment]
Any updates on this? I think optgroups are very important to have.

**Comment by fabianlindfors** [comment]
Unfortunately I haven't had much time to spend on multi.js. I do agree that optgroups would be a great addition but I probably won't be able to implement it soon. If you'd like to try implementing them, feel free to create a PR and I'll make sure to check it out.

**Comment by fabianlindfors** [comment]
Hello again!

I finally got around to implementing optgroups and support is available with the just released 0.3.0. You might not be using multi.js still but thought I should let you know.

Thank you for your suggestion!
