### ISSUE TITLE
call back function when clicking disabled options?

### ISSUE THREAD

**Issue by 2x2p** [fabianlindfors/multi.js#33]
in order to report to the UX why a selection option is currently disabled a call back function would be be useful much alike attaching a function to limit_reached, Only this one should be sending back the option.value and option.text of the clicked disabled item for it to be further handled externally.

**Comment by fabianlindfors** [comment]
Nice idea! If you implement this feature and submit a pull request I'd be happy to accept it. A bit too busy currently to work on this :)
