### ISSUE TITLE
Preselected items

### ISSUE THREAD

**Issue by ilovetacos** [fabianlindfors/multi.js#37]
Hi, thank you for the good work! I was wondering if there is a possibility to set preselected items?

**Comment by GeekJosh** [comment]
It is - just make sure the options are selected in the original select element before initializing multi.js and it'll preselect them

**Comment by fabianlindfors** [comment]
Thanks for chiming in @GeekJosh, you're totally right! If you change the selected items after multi.js has been initialized you can also trigger the `change` event to have them update.
