### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by ciberpiranha** [fabianlindfors/multi.js#41]
I think that readme is a bit incomplete. My  proposal for improve it is this:

In  installation or usage via NPM/Yarn I  suggest to specify different ways to use it via modules:

For example import via js:
```
import multi from "multi.js/dist/multi-es6.min.js";
import 'multi.js/src/multi.css';
var select = document.getElementById("fruit_select");
multi(select);
```
Or another option is import js via module and styles via SASS:
`@import 'multi.js/src/multi.css';`

If you want I can  make a PR including these two steps in README

Thanx!

**Comment by fabianlindfors** [comment]
Please do make a PR, those are always appreciated! :)

**Comment by ciberpiranha** [comment]
This is the PR:https://github.com/fabianlindfors/multi.js/pull/42.
Thanx!
