### ISSUE TITLE
Why I get “Uncaught Error: Cannot find module 'multi.js' ” when module is installed globally?

### ISSUE THREAD

**Issue by wasimaftab** [fabianlindfors/multi.js#43]
I have described this issue in detail in this  StackOverflow [link](https://stackoverflow.com/questions/64027976/why-i-get-uncaught-error-cannot-find-module-multi-js-when-module-is-instal)

**Comment by ciberpiranha** [comment]
Try my solution in Issue #41 to use and import multijs vía npm or yarn.

**Comment by fabianlindfors** [comment]
Hi! I'll close this for now. The readme should better reflect how to import as a module thanks to #42.
