### ISSUE TITLE
Required Validation

### ISSUE THREAD

**Issue by MinhInBlack** [fabianlindfors/multi.js#48]
I noticed the plugin doesn't bring over "required" attributes or a functionality that validates if the field is required then no submission can be made. Is there a fix to this or is there an ability to do so already that I'm just not aware?

**Comment by fabianlindfors** [comment]
Hi!

Unfortunately, this is not possible. The `required` attribute only works on HTML form elements and hence can't be put on the multi.js wrapper. Putting it on the underlying `select` element is possible but it most likely won't work as multi.js will hide it using CSS.
