### ISSUE TITLE
Disable or readonly

### ISSUE THREAD

**Issue by andreescocard** [fabianlindfors/multi.js#49]
How can i let the multi select disabled or in readonly mode?
Tried some parameters but none worked.
Thanks

**Comment by andreescocard** [comment]
Solved in a ugly way haha
`.multi-wrapper .item{
    pointer-events:none;
}`

**Comment by fabianlindfors** [comment]
Hi, @andreescocard! Multi.js supports the standard HTML `disabled` attribute on `option` elements and I would recommend using that instead!

**Comment by andreescocard** [comment]
I did that, but won't work.

**Comment by fabianlindfors** [comment]
In that case, it's not possibly with the way the HTML standard is designed. `required` will only work for the traditional HTML form elements.
