### ISSUE TITLE
Block header

### ISSUE THREAD

**Issue by EduardoAcunaCoronado** [fabianlindfors/multi.js#52]
Can I block header label?

**Comment by fabianlindfors** [comment]
Hi! Which header are you referring to? Also, what are you referring to when you say block?

**Comment by EduardoAcunaCoronado** [comment]
Hold the title up if I scroll the list.

**Comment by fabianlindfors** [comment]
Hi! Sorry about the late reply.

There is no built-in way to achieve this. You might be able to achieve it by writing some custom CSS for the titles but I won't be able to help with that.
