### ISSUE TITLE
Submit to NPM

### ISSUE THREAD

**Issue by rodymolenaar** [fabianlindfors/multi.js#7]
I'd love to be able to use this library through NPM / Yarn. Making updating to the newest version easier.

NOTE: There already are libraries using the name multi.js, not sure if that is a potential issue.

Thanks for the amazing work :)

**Comment by fabianlindfors** [comment]
Hi! This is more than a year late but multi.js has been available on npm for some time but I forgot to close this issue. Hope you are still enjoying it!
